// @ts-check
const { generateDeclaration, Placeholder } = require("@techcross/ts-migrate");
const fs = require("fs");
const moduleConfig = require("./moduleConfig.json");

/**
 * @param {string[]} files
 * @param {string[]} result
 */
function collectFiles(files, result) {
    files.forEach(file => {
        if (moduleConfig.module[file]) {
            collectFiles(moduleConfig.module[file], result);
        }
        else if (result.indexOf(file) === -1) {
            result.push(file);
        }
    });
    return result;
}

(async () => {
    const files = collectFiles(["cocos2d", "extensions"], []);
    await generateDeclaration(files, {
        additionalTSCode: `
        // generated by ts-migrate, please do not edit this file
        type int = number;
        type long = number;
        type Bool = boolean;
        namespace cc
        {
            declare var view: EGLView;
            export { view };
            declare var kmMat4: any;
            export { kmMat4 }

            export class CanvasContextWrapper{}
            export class Scheduler{}
            export class Texture2D{}
            export class DirectorDelegate{}
            export class Class{}
            export class Scale9Sprite extends Node {}
        }
        namespace ccui
        {
            declare var Scale9Sprite: cc.Scale9Sprite;
            export { Scale9Sprite }
        }
        `,
        tsOptions: {
            outFile: "build/cocos2d.d.ts",
        },
        methodDeclarationPluginOptions: {
            normalizeSignatureMethodNames: ["init", "initWithString", "initWithDuration", "initWithAction", "onTouchBegan"]
        },
        classPluginOptions: {
            classCreator: `cc.Class.extend(${Placeholder.Body})`,
            classExtender: `${Placeholder.Name}.extend(${Placeholder.Body})`,
        },
        namespacePluginOptions: {
            globalVarMap: {
                cc: "cc",
                ccui: "ccui",
            },
            topFunctionArgumentsRange: { min: -1, max: -1 },
            prevertParseNames: ["prototype", "proto", "_tmp", "rendererWebGL", "AABB", "Codec"],
            removeGlobalVars: ["_p", "spine", "sp", "ccs", "cclegacy"],
        },
        tsdReplacer: (code) => {
            return code
                .replace(/Uint8Array<.*>/g, "Uint8Array")
                .replace(/Float32Array<.*>/g, "Float32Array")
                .replace(/override /g, "")
        }
    });
})()