// @ts-check
const { generateDeclaration, ClassPluginPlaceholder } = require("@techcross/ts-migrate");
const fs = require("fs");
const moduleConfig = require("./moduleConfig.json");

/**
 * @param {string[]} files
 * @param {string[]} result
 */
function collectFiles(files, result) {
    files.forEach(file => {
        if (moduleConfig.module[file]) {
            collectFiles(moduleConfig.module[file], result);
        }
        else if (result.indexOf(file) === -1) {
            result.push(file);
        }
    });
    return result;
}

(async () => {
    const files = collectFiles(["cocos2d", "extensions"], []);
    await generateDeclaration(files, {
        additionalTSCode: `
        /**
         * generated by ts-migrate, please do not edit this file
         */
        declare var __generated;
        type int = number;
        type long = number;
        type Bool = boolean;
        namespace cc
        {
            declare var view: EGLView;
            export { view };
            declare var kmMat4: any;
            export { kmMat4 }

            export class CanvasContextWrapper{}
            export class Scheduler{}
            export class Texture2D{}
            export class DirectorDelegate{}
            export class Class{}
            export class Scale9Sprite extends Node {}
        }
        namespace ccui
        {
            declare var Scale9Sprite: cc.Scale9Sprite;
            export { Scale9Sprite }
        }
        namespace ccs
        {
            export class Shape{}
        }
        `,
        tsOptions: {
            outFile: "build/cocos2d.d.ts",
        },
        methodDeclarationPluginOptions: {
            normalizeSignatureMethodNames: ["init", "initWithString", "initWithDuration", "initWithAction", "initWithFile", "startWithTarget", "onTouchBegan", "onTouchCancelled", "onEnter"]
        },
        classPluginOptions: {
            classCreators: [
                `cc.Class.extend(${ClassPluginPlaceholder.Body})`,
                `ccs.Class.extend(${ClassPluginPlaceholder.Body})`,
            ],
            classExtenders: [`${ClassPluginPlaceholder.Name}.extend(${ClassPluginPlaceholder.Body})`],
        },
        namespacePluginOptions: {
            globalVarMap: {
                cc: "cc",
                ccui: "ccui",
                ccs: "ccs",
            },
            topFunctionArgumentsRange: { min: -1, max: -1 },
            prevertParseNames: ["prototype", "create", "proto", "_tmp", "rendererWebGL", "AABB", "Codec"],
            removeGlobalVars: ["_p", "spine", "sp", "ccs", "cclegacy"],
        },
        tsIgnorePluginOptions: {
            classDeclaration: (_, p) => p && "We need to ignore the TS2416 error because cocos2d uses the same static factory method name \"create\" to create objects, which is not currently supported by Typescript.",
            classElement: (n, _, e) => 
            (n === "ParallaxNode" && e === "addChild")
            || (n === "ArmatureAnimation" && e === "play")
            || (n === "Tween" && e === "play")
             ? "We need to ignore the TS2416 error because cocos2d uses different signatures at different inheritance levels." : undefined
        },
        tsdReplacer: (code) => {
            return code
                .replace(/Uint8Array<.*>/g, "Uint8Array")
                .replace(/Float32Array<.*>/g, "Float32Array")
                .replace(/Uint32Array<.*>/g, "Uint32Array")
                .replace(/override /g, "")
        }
    });
})()